source 'https://rubygems.org'
ruby '2.2.2'
gem 'rails', '4.2.1'
gem 'sass-rails'
gem 'pg'
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder'
gem 'unicorn'
group :development do
	gem 'better_errors'
	gem 'spring'
end
