source 'https://rubygems.org'
ruby '2.2.3'
gem 'rails', '4.2.5'
gem 'pg'
gem 'thin'
gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder'
gem 'bootstrap-sass'
group :development do
  gem 'web-console'
  gem 'spring'
end
