source 'https://rubygems.org'
ruby '2.2.3'
gem 'rails', '4.2.5'
gem 'pg'
gem 'thin'
gem 'sass-rails'
gem 'uglifier'
gem 'font-awesome-rails'
gem 'coffee-rails'
gem 'videojs_rails'
gem 'jquery-rails'
gem 'closure_tree'
gem 'devise'
gem 'turbolinks'
gem 'jbuilder'
gem 'bootstrap-sass'
gem 'rails-treeview', github: 'pierreprevoteau/rails-treeview'
gem 'rails-gtreetable', github: 'pierreprevoteau/rails-gtreetable'
group :development do
  gem 'web-console'
  gem 'spring'
end
