development:
  adapter: postgresql
  encoding: utf8
  database: kermit_development
  pool: 5
  username: postgres
  password: 

test:
  adapter: postgresql
  encoding: utf8
  database: kermit_test
  pool: 5
  username: postgres
  password: 

production:
  adapter: postgresql
  encoding: utf8
  database: kermit_production
  pool: 5
  username: postgres
  password: postgres
