development:
  adapter: postgresql
  encoding: utf8
  database: <%= ENV["DB_CONNECT_DATABASE"] %>
  pool: 5
  username: <%= ENV["DB_CONNECT_USERNAME"] %>
  password: <%= ENV["DB_CONNECT_PASSWORD"] %>
  host: <%= ENV["DB_CONNECT_HOST"] %>
  port: <%= ENV["DB_CONNECT_PORT"] %> 

test:
  adapter: postgresql
  encoding: utf8
  database: <%= ENV["DB_CONNECT_DATABASE"] %>
  pool: 5
  username: <%= ENV["DB_CONNECT_USERNAME"] %>
  password: <%= ENV["DB_CONNECT_PASSWORD"] %>
  host: <%= ENV["DB_CONNECT_HOST"] %>
  port: <%= ENV["DB_CONNECT_PORT"] %> 

production:
  adapter: postgresql
  encoding: utf8
  database: <%= ENV["DB_CONNECT_DATABASE"] %>
  pool: 5
  username: <%= ENV["DB_CONNECT_USERNAME"] %>
  password: <%= ENV["DB_CONNECT_PASSWORD"] %>
  host: <%= ENV["DB_CONNECT_HOST"] %>
  port: <%= ENV["DB_CONNECT_PORT"] %> 
