development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: kermit_development
  pool:     5
  username: pierreprevoteau
  password:
  template: template0

test:
  adapter: postgresql
  database: travis_ci_test
  username: postgres

production:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: kermit_production
  pool:     5
  username: bao
  password:
  template: template0
