# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa20793c035093ea5027b38ac32ae877223180cbd01d8092a74511bd7b2c548bffb9c5639a7fdc1afd3ab56122456761863d95e51dd63a56d9e5acd1a1a1f3d1

test:
  secret_key_base: 60bc03b06e447f9e241faaac26c3a6982ded5b3131744eb56834554fc9561aee8b12b8db7c456fa2af5b8ab9cb9eee580e87666428dd1fc319ce6729d1222371

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
